// <auto-generated />

namespace PovScene.SceneDescription.Items.ObjectModifiers
{
    using System;
    using Libraries;
    using Output;
    using Values;

    [BlockElement(Keyword.Normal)]
    public class Normal : PigmentOrNormal
    {
        [Output]
        public SlopeMap SlopeMap { get; set; }

        [Output]
        public BumpMap BumpMap { get; set; }
        
        public class Plain : Normal
        {
            public Plain()
            {
            }
        }

        public class Patterned : Normal
        {
            [Output]
            public Pattern Pattern { get; set; }

            public Patterned(Pattern pattern = null)
            {
                this.Pattern = pattern;
            }
        }

        public static implicit operator Normal(Pattern pattern)
        {
            if (pattern.AllowNormal)
            {
                return new Patterned(pattern);
            }
            else
            {
                throw new InvalidCastException("That pattern can't be casted to a normal.");
            }
        }
    }
}